spring.application.name=LoanLite

# spring.datasource.url moved to profile files (application-dev.properties / application-prod.properties)
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.port=8080
